defmodule FairDinkum.Repo.Migrations.InitialMigration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:players, primary_key: false) do
      add :type, :text
      add :name, :text
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop table(:players)
  end
end